# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [43]:
# Import torch
import torch

# Create random tensor
tensor_A= torch.rand(7,7)
print(tensor_A,tensor_A.shape)

tensor([[0.7213, 0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196],
        [0.2147, 0.2816, 0.6679, 0.7878, 0.5070, 0.3055, 0.7738],
        [0.2259, 0.3826, 0.9717, 0.5921, 0.5352, 0.6686, 0.3781],
        [0.9278, 0.0922, 0.3625, 0.4136, 0.2943, 0.3762, 0.8099],
        [0.7743, 0.5278, 0.9356, 0.1470, 0.2019, 0.7259, 0.4731],
        [0.0444, 0.1539, 0.1956, 0.8861, 0.7264, 0.8868, 0.1278],
        [0.0125, 0.1721, 0.5535, 0.4012, 0.1849, 0.8640, 0.3388]]) torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [44]:
# Create another random tensor
tensor_B = torch.rand(1,7)
# Perform matrix multiplication
multi_Tensor =torch.matmul(tensor_A,tensor_B.T)
multi_Tensor , multi_Tensor.shape

(tensor([[1.7488],
         [2.0786],
         [2.0697],
         [1.5989],
         [1.7942],
         [1.9002],
         [1.4212]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [45]:
# Set manual seed
torch.random.manual_seed(0)

# Create two random tensors
tensor_C= torch.rand(7,7)
tensor_D= torch.rand(1,7)

# Matrix multiply tensors
mult_CD =torch.matmul(tensor_C,tensor_D.T)
mult_CD , mult_CD.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [46]:
# Set random seed on the GPU
torch.random.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [40]:
# Set random seed
torch.random.manual_seed(1234)
# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device: "+ device)
# Create two random tensors on GPU
tensor_1 =torch.rand(2,3)
tensor_2 =torch.rand(2,3)
tensor_Gpu1 = tensor_1.to(device)
tensor_Gpu2 = tensor_2.to(device)
print(tensor_Gpu1)
print(tensor_Gpu2)


Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [34]:
# Perform matmul on tensor_A and tensor_B
mult_tensor = torch.matmul(tensor_Gpu1 , tensor_Gpu2.T)
print(mult_tensor,mult_tensor.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [35]:
# Find max
Max_number = torch.max(mult_tensor)
print(Max_number)
# Find min
Min_number = torch.min(mult_tensor)
print(Min_number)

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [37]:
# Find arg max
Arg_Max =torch.argmax(mult_tensor)
print(Arg_Max)
# Find arg min
Arg_Min =torch.argmin(mult_tensor)
print(Arg_Min)

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [41]:
# Set seed
torch.random.manual_seed(7)
# Create random tensor

Tensor_A = torch.rand(1,1,1,10)

# Remove single dimensions

Tensor_B = Tensor_A.squeeze()

# Print out tensors and their shapes
print(Tensor_A,Tensor_A.shape)
print(Tensor_B,Tensor_B.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
